# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Mon Jan 20 14:09:14 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtWidgets
from PyQt5 import QtCore
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_out = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_out.setText("")
        self.lineEdit_out.setObjectName("lineEdit_out")
        self.gridLayout_2.addWidget(self.lineEdit_out, 1, 2, 1, 1)
        self.pushButton_out = QtWidgets.QPushButton(self.tab)
        self.pushButton_out.setObjectName("pushButton_out")
        self.gridLayout_2.addWidget(self.pushButton_out, 1, 1, 1, 1)
        self.pushButton_in = QtWidgets.QPushButton(self.tab)
        self.pushButton_in.setObjectName("pushButton_in")
        self.gridLayout_2.addWidget(self.pushButton_in, 0, 1, 1, 1)
        self.lineEdit_in = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_in.setText("")
        self.lineEdit_in.setObjectName("lineEdit_in")
        self.gridLayout_2.addWidget(self.lineEdit_in, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 1, 0, 2, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.padDefTable = QtWidgets.QTableWidget(self.tab_2)
        self.padDefTable.setObjectName("padDefTable")
        self.padDefTable.setColumnCount(0)
        self.padDefTable.setRowCount(0)
        self.gridLayout_5.addWidget(self.padDefTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.compDefTable = QtWidgets.QTableWidget(self.tab_3)
        self.compDefTable.setObjectName("compDefTable")
        self.compDefTable.setColumnCount(0)
        self.compDefTable.setRowCount(0)
        self.gridLayout_6.addWidget(self.compDefTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.compTable = QtWidgets.QTableWidget(self.tab_4)
        self.compTable.setObjectName("compTable")
        self.compTable.setColumnCount(0)
        self.compTable.setRowCount(0)
        self.gridLayout_7.addWidget(self.compTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "PcadAttr", None, -1))
        self.pushButton_out.setText(QtWidgets.QApplication.translate("MainWindow", "choose", None, -1))
        self.pushButton_in.setText(QtWidgets.QApplication.translate("MainWindow", "choose", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Input file", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Output file", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Generate", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Description:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Availible actions:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Processing", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Pad definition", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Component definition", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Components", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtWidgets.QApplication.translate("MainWindow", "Reports", None, -1))

