# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(944, 669)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page0)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tab_widget0 = QtWidgets.QTabWidget(self.page0)
        self.tab_widget0.setObjectName("tab_widget0")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(2)
        self.tableWidget_10.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        self.gridLayout_33.addWidget(self.tableWidget_10, 0, 0, 4, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_33.addWidget(self.pushButton_27, 0, 1, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_33.addWidget(self.pushButton_28, 1, 1, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_33.addWidget(self.pushButton_29, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 371, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_33.addItem(spacerItem, 3, 1, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_51 = QtWidgets.QLabel(self.groupBox_12)
        self.label_51.setObjectName("label_51")
        self.gridLayout_32.addWidget(self.label_51, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_12)
        self.label_52.setObjectName("label_52")
        self.gridLayout_32.addWidget(self.label_52, 1, 0, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_32.addWidget(self.lineEdit_49, 1, 1, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_32.addWidget(self.pushButton_30, 1, 2, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_32.addWidget(self.lineEdit_48, 0, 1, 1, 2)
        self.gridLayout_33.addWidget(self.groupBox_12, 4, 0, 1, 2)
        self.tab_widget0.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_26.addWidget(self.pushButton_20, 0, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_26.addWidget(self.pushButton_21, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_27.addWidget(self.lineEdit_45, 0, 1, 2, 2)
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_27.addWidget(self.pushButton_23, 0, 6, 2, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_6)
        self.label_44.setObjectName("label_44")
        self.gridLayout_27.addWidget(self.label_44, 0, 0, 2, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_27.addWidget(self.lineEdit_44, 0, 5, 2, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_6)
        self.label_45.setObjectName("label_45")
        self.gridLayout_27.addWidget(self.label_45, 0, 3, 2, 1)
        self.gridLayout_26.addWidget(self.groupBox_6, 4, 0, 1, 2)
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_26.addWidget(self.pushButton_22, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem1, 3, 1, 1, 1)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(2)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        self.gridLayout_26.addWidget(self.tableWidget_8, 0, 0, 4, 1)
        self.tab_widget0.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(4)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        self.gridLayout_29.addWidget(self.tableWidget_9, 0, 0, 4, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_29.addWidget(self.pushButton_24, 0, 1, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_29.addWidget(self.pushButton_25, 1, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_29.addWidget(self.pushButton_26, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 371, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_29.addItem(spacerItem2, 3, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_47 = QtWidgets.QLabel(self.groupBox_11)
        self.label_47.setObjectName("label_47")
        self.gridLayout_28.addWidget(self.label_47, 0, 0, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_28.addWidget(self.lineEdit_47, 0, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_11)
        self.label_49.setObjectName("label_49")
        self.gridLayout_28.addWidget(self.label_49, 0, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_28.addWidget(self.comboBox_5, 0, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_11)
        self.label_48.setObjectName("label_48")
        self.gridLayout_28.addWidget(self.label_48, 1, 0, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_28.addWidget(self.lineEdit_46, 1, 1, 1, 1)
        self.gridLayout_28.setColumnStretch(3, 1)
        self.gridLayout_29.addWidget(self.groupBox_11, 4, 0, 1, 2)
        self.tab_widget0.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_30.addWidget(self.checkBox_21, 0, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_30.addWidget(self.checkBox_22, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(484, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem3, 1, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_30.addWidget(self.checkBox_23, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 483, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem4, 3, 0, 1, 1)
        self.tab_widget0.addTab(self.tab_9, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_16)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_31.addWidget(self.checkBox_24, 0, 0, 1, 2)
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab_16)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_31.addWidget(self.checkBox_25, 1, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(365, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem5, 1, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_16)
        self.label_50.setObjectName("label_50")
        self.gridLayout_31.addWidget(self.label_50, 2, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_16)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_31.addWidget(self.comboBox_6, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 481, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem6, 3, 1, 1, 1)
        self.tab_widget0.addTab(self.tab_16, "")
        self.gridLayout_7.addWidget(self.tab_widget0, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tab_widget1 = QtWidgets.QTabWidget(self.page1)
        self.tab_widget1.setObjectName("tab_widget1")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem7, 6, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_19.addWidget(self.pushButton_10, 1, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_19.addWidget(self.pushButton_11, 2, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem8, 6, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_19.addWidget(self.pushButton_12, 3, 2, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_19.addWidget(self.checkBox_18, 0, 1, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_19.addWidget(self.checkBox_17, 0, 0, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.gridLayout_19.addWidget(self.tableWidget_3, 1, 0, 4, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_20.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_20.addWidget(self.lineEdit_30, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_20.addWidget(self.label_31, 1, 0, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_20.addWidget(self.lineEdit_31, 1, 1, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_3, 5, 0, 1, 3)
        self.tab_widget1.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_21.addWidget(self.pushButton_14, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem9, 3, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_21.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(8)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        self.gridLayout_21.addWidget(self.tableWidget_5, 0, 0, 4, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_21.addWidget(self.pushButton_15, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_22.addWidget(self.label_32, 2, 0, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_22.addWidget(self.lineEdit_33, 6, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_22.addWidget(self.label_35, 2, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_22.addWidget(self.label_37, 6, 2, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_22.addWidget(self.lineEdit_39, 6, 3, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_22.addWidget(self.lineEdit_34, 2, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setObjectName("label_38")
        self.gridLayout_22.addWidget(self.label_38, 6, 0, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_22.addWidget(self.lineEdit_35, 5, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_22.addWidget(self.lineEdit_32, 5, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_22.addWidget(self.label_33, 0, 0, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_22.addWidget(self.checkBox_19, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setObjectName("label_36")
        self.gridLayout_22.addWidget(self.label_36, 5, 2, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_22.addWidget(self.checkBox_20, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_22.addWidget(self.label_34, 5, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.tab_widget1.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_12)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_18.addWidget(self.checkBox_15, 0, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_12)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_18.addWidget(self.checkBox_16, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(621, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 1, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 535, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem11, 2, 1, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_18.addWidget(self.lineEdit_29, 0, 1, 1, 1)
        self.tab_widget1.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem12 = QtWidgets.QSpacerItem(627, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem12, 1, 3, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_13)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_17.addWidget(self.checkBox_14, 1, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_13)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_17.addWidget(self.checkBox_12, 0, 0, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 535, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem13, 2, 0, 1, 2)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_17.addWidget(self.lineEdit_28, 0, 2, 1, 1)
        self.tab_widget1.addTab(self.tab_13, "")
        self.gridLayout_8.addWidget(self.tab_widget1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab_widget2 = QtWidgets.QTabWidget(self.page2)
        self.tab_widget2.setObjectName("tab_widget2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout_6.addWidget(self.tableWidget, 0, 0, 4, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 2, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 280, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem14, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 4, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 2, 6, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 3, 1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_6.addWidget(self.groupBox, 4, 0, 1, 2)
        self.tab_widget2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 1, 2, 3, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_5.addWidget(self.checkBox_3, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_5.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 2, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 3, 1, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.gridLayout_4.addWidget(self.tableWidget_4, 0, 0, 4, 1)
        self.tab_widget2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_36.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_15.addWidget(self.lineEdit_36, 1, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 564, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem16, 2, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem17, 1, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_15.addWidget(self.checkBox_4, 1, 0, 1, 1)
        self.tab_widget2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_11.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_11.addWidget(self.lineEdit_11, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_11.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_11.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_11.addWidget(self.lineEdit_9, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 1, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_11.addWidget(self.lineEdit_10, 2, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_11.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 2, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_11.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_11.addWidget(self.checkBox_6, 2, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_11.addWidget(self.checkBox_7, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_12.addWidget(self.lineEdit_12, 0, 3, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_12.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_12.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 0, 2, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_12.addWidget(self.lineEdit_15, 3, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_12.addWidget(self.lineEdit_16, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 1, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_12.addWidget(self.lineEdit_17, 2, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_12.addWidget(self.lineEdit_18, 1, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        self.label_24.setObjectName("label_24")
        self.gridLayout_12.addWidget(self.label_24, 2, 2, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_12.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_12.addWidget(self.checkBox_8, 2, 0, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_12.addWidget(self.checkBox_9, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_13.addWidget(self.lineEdit_20, 0, 3, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_13.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_13.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 0, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_13.addWidget(self.lineEdit_23, 3, 3, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_13.addWidget(self.lineEdit_24, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setObjectName("label_26")
        self.gridLayout_13.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 3, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 1, 2, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_13.addWidget(self.lineEdit_25, 2, 3, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_13.addWidget(self.lineEdit_26, 1, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_9)
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_9)
        self.label_30.setObjectName("label_30")
        self.gridLayout_13.addWidget(self.label_30, 2, 2, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_13.addWidget(self.lineEdit_27, 1, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_13.addWidget(self.checkBox_10, 2, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_13.addWidget(self.checkBox_11, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_14.addWidget(self.checkBox_13, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_10, 3, 0, 1, 1)
        self.tab_widget2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_37.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_16.addWidget(self.lineEdit_37, 0, 2, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_38.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_16.addWidget(self.lineEdit_38, 2, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(539, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem18, 2, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_16.addWidget(self.label_46, 0, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_16.addWidget(self.checkBox_5, 2, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 533, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem19, 3, 0, 1, 1)
        self.tab_widget2.addTab(self.tab_5, "")
        self.gridLayout_2.addWidget(self.tab_widget2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tab_widget3 = QtWidgets.QTabWidget(self.page3)
        self.tab_widget3.setObjectName("tab_widget3")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_14)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(1)
        self.tableWidget_6.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        self.gridLayout_23.addWidget(self.tableWidget_6, 0, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(377, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem20, 0, 1, 1, 1)
        self.gridLayout_23.setColumnStretch(1, 1)
        self.tab_widget3.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab_15)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_24.addWidget(self.pushButton_16, 0, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_24.addWidget(self.pushButton_17, 1, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_24.addWidget(self.pushButton_18, 2, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_25.addWidget(self.lineEdit_41, 2, 1, 1, 2)
        self.label_42 = QtWidgets.QLabel(self.groupBox_5)
        self.label_42.setObjectName("label_42")
        self.gridLayout_25.addWidget(self.label_42, 4, 0, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_25.addWidget(self.lineEdit_40, 0, 1, 2, 2)
        self.label_39 = QtWidgets.QLabel(self.groupBox_5)
        self.label_39.setObjectName("label_39")
        self.gridLayout_25.addWidget(self.label_39, 0, 0, 2, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_5)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.gridLayout_25.addWidget(self.label_43, 0, 4, 4, 2)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_25.addWidget(self.lineEdit_42, 3, 1, 1, 2)
        self.label_40 = QtWidgets.QLabel(self.groupBox_5)
        self.label_40.setObjectName("label_40")
        self.gridLayout_25.addWidget(self.label_40, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_5)
        self.label_41.setObjectName("label_41")
        self.gridLayout_25.addWidget(self.label_41, 3, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_25.addWidget(self.pushButton_19, 4, 5, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem21, 0, 3, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_25.addWidget(self.lineEdit_43, 4, 1, 1, 4)
        self.gridLayout_25.setColumnStretch(4, 1)
        self.gridLayout_24.addWidget(self.groupBox_5, 4, 0, 1, 2)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem22, 3, 1, 1, 1)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(4)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        self.gridLayout_24.addWidget(self.tableWidget_7, 0, 0, 4, 1)
        self.tab_widget3.addTab(self.tab_15, "")
        self.gridLayout_9.addWidget(self.tab_widget3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page3)
        self.gridLayout.addWidget(self.stackedWidget, 1, 1, 1, 1)
        self.labelCurrentSetting = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelCurrentSetting.setFont(font)
        self.labelCurrentSetting.setObjectName("labelCurrentSetting")
        self.gridLayout.addWidget(self.labelCurrentSetting, 0, 1, 1, 1)
        self.settings_tree = QtWidgets.QTreeWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.settings_tree.setFont(font)
        self.settings_tree.setObjectName("settings_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.settings_tree.header().setVisible(False)
        self.gridLayout.addWidget(self.settings_tree, 0, 0, 2, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.tab_widget0.setCurrentIndex(0)
        self.tab_widget1.setCurrentIndex(1)
        self.tab_widget2.setCurrentIndex(0)
        self.tab_widget3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Path"))
        self.pushButton_27.setText(_translate("Form", "Add"))
        self.pushButton_28.setText(_translate("Form", "Copy"))
        self.pushButton_29.setText(_translate("Form", "Delete"))
        self.groupBox_12.setTitle(_translate("Form", "Settings"))
        self.label_51.setText(_translate("Form", "Name"))
        self.label_52.setText(_translate("Form", "Path"))
        self.pushButton_30.setText(_translate("Form", "..."))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_6), _translate("Form", "Settings import/export"))
        self.pushButton_20.setText(_translate("Form", "Add"))
        self.pushButton_21.setText(_translate("Form", "Copy"))
        self.groupBox_6.setTitle(_translate("Form", "Hotkey"))
        self.pushButton_23.setText(_translate("Form", "..."))
        self.label_44.setText(_translate("Form", "Name"))
        self.label_45.setText(_translate("Form", "Shortcut"))
        self.pushButton_22.setText(_translate("Form", "Delete"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Shortcut"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_7), _translate("Form", "Hotkeys"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Toolbar name"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Hotkey"))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Shortcut"))
        self.pushButton_24.setText(_translate("Form", "Add"))
        self.pushButton_25.setText(_translate("Form", "Copy"))
        self.pushButton_26.setText(_translate("Form", "Delete"))
        self.groupBox_11.setTitle(_translate("Form", "Tool button"))
        self.label_47.setText(_translate("Form", "Name"))
        self.label_49.setText(_translate("Form", "Hotkey"))
        self.label_48.setText(_translate("Form", "Toolbar name"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_8), _translate("Form", "Toolbar"))
        self.checkBox_21.setText(_translate("Form", "Show visual editor"))
        self.checkBox_22.setText(_translate("Form", "Show tape types"))
        self.checkBox_23.setText(_translate("Form", "Show Board"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_9), _translate("Form", "View"))
        self.checkBox_24.setText(_translate("Form", "Clear component images on startup"))
        self.checkBox_25.setText(_translate("Form", "Clear logs on startup"))
        self.label_50.setText(_translate("Form", "Log level"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_16), _translate("Form", "Logging"))
        self.pushButton_10.setText(_translate("Form", "Add"))
        self.pushButton_11.setText(_translate("Form", "Copy"))
        self.pushButton_12.setText(_translate("Form", "Delete"))
        self.checkBox_18.setText(_translate("Form", "Value attribute"))
        self.checkBox_17.setText(_translate("Form", "Component names"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Symbols"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Replace to"))
        self.groupBox_3.setTitle(_translate("Form", "Replacement"))
        self.label.setText(_translate("Form", "Original symbols"))
        self.label_31.setText(_translate("Form", "Replace to"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_10), _translate("Form", "Symbols replacement"))
        self.pushButton_14.setText(_translate("Form", "Copy"))
        self.pushButton_13.setText(_translate("Form", "Add"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Use"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Replace"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Type"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Family"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Face"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Height"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("Form", "StrokeWidth"))
        self.pushButton_15.setText(_translate("Form", "Delete"))
        self.groupBox_4.setTitle(_translate("Form", "Font settings"))
        self.label_32.setText(_translate("Form", "Replace if exists"))
        self.label_35.setText(_translate("Form", "Face"))
        self.label_37.setText(_translate("Form", "Stroke width"))
        self.label_38.setText(_translate("Form", "Type"))
        self.label_33.setText(_translate("Form", "Use"))
        self.label_36.setText(_translate("Form", "Height"))
        self.label_34.setText(_translate("Form", "Name"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_11), _translate("Form", "Font adding"))
        self.checkBox_15.setText(_translate("Form", "Change RefPointSize to"))
        self.checkBox_16.setText(_translate("Form", "Replace if exists"))
        self.lineEdit_29.setText(_translate("Form", "1.0"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_12), _translate("Form", "RefPointSize"))
        self.checkBox_14.setText(_translate("Form", "Replace if exists"))
        self.checkBox_12.setText(_translate("Form", "Change solder swell to"))
        self.lineEdit_28.setText(_translate("Form", "0.01"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_13), _translate("Form", "Solder swell"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Use"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Text"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Ignore"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "DIP/SMD"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "CompType"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Attribute List"))
        self.pushButton_4.setText(_translate("Form", "Add"))
        self.pushButton_5.setText(_translate("Form", "Copy"))
        self.pushButton_6.setText(_translate("Form", "Delete"))
        self.groupBox.setTitle(_translate("Form", "Component"))
        self.label_4.setText(_translate("Form", "Type"))
        self.label_3.setText(_translate("Form", "CompType"))
        self.label_2.setText(_translate("Form", "DIP/SMD"))
        self.label_6.setText(_translate("Form", "Use"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Attribute"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Default Value"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Visible"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Side"))
        self.label_7.setText(_translate("Form", "Ignore"))
        self.label_5.setText(_translate("Form", "Text"))
        self.pushButton_7.setText(_translate("Form", "Add"))
        self.pushButton_8.setText(_translate("Form", "Copy"))
        self.pushButton_9.setText(_translate("Form", "Delete"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab), _translate("Form", "Attribute assigment"))
        self.pushButton_2.setText(_translate("Form", "Copy"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.groupBox_2.setTitle(_translate("Form", "Attribute"))
        self.label_8.setText(_translate("Form", "Attribute"))
        self.label_12.setText(_translate("Form", "Description"))
        self.label_9.setText(_translate("Form", "Default Value"))
        self.label_10.setText(_translate("Form", "Visible"))
        self.label_11.setText(_translate("Form", "Side"))
        self.pushButton_3.setText(_translate("Form", "Delete"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Attribute"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Default Value"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Visible"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Side"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Description"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_2), _translate("Form", "Attribute types"))
        self.lineEdit_36.setText(_translate("Form", "2"))
        self.checkBox_4.setText(_translate("Form", "Use warning  distance between arithmetic and geometric centers in mm"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_3), _translate("Form", "PnP"))
        self.groupBox_7.setTitle(_translate("Form", "Group A"))
        self.lineEdit_5.setText(_translate("Form", "8"))
        self.lineEdit_11.setText(_translate("Form", "2"))
        self.lineEdit_4.setText(_translate("Form", "0"))
        self.label_14.setText(_translate("Form", "to"))
        self.lineEdit_8.setText(_translate("Form", "5"))
        self.lineEdit_9.setText(_translate("Form", "1"))
        self.label_13.setText(_translate("Form", "Pad count from "))
        self.label_19.setText(_translate("Form", "or more then "))
        self.label_16.setText(_translate("Form", "to"))
        self.lineEdit_10.setText(_translate("Form", "6"))
        self.lineEdit_6.setText(_translate("Form", "6"))
        self.label_15.setText(_translate("Form", "Size in mm from"))
        self.label_20.setText(_translate("Form", "or more then "))
        self.lineEdit_7.setText(_translate("Form", "0"))
        self.checkBox_6.setText(_translate("Form", "Use warning when pads less then"))
        self.checkBox_7.setText(_translate("Form", "Use warning when size in mm less then "))
        self.groupBox_8.setTitle(_translate("Form", "Group B"))
        self.lineEdit_12.setText(_translate("Form", "44"))
        self.lineEdit_13.setText(_translate("Form", "10"))
        self.lineEdit_14.setText(_translate("Form", "8"))
        self.label_17.setText(_translate("Form", "to"))
        self.lineEdit_15.setText(_translate("Form", "18"))
        self.lineEdit_16.setText(_translate("Form", "8"))
        self.label_18.setText(_translate("Form", "Pad count from "))
        self.label_21.setText(_translate("Form", "or more then "))
        self.label_22.setText(_translate("Form", "to"))
        self.lineEdit_17.setText(_translate("Form", "40"))
        self.lineEdit_18.setText(_translate("Form", "20"))
        self.label_23.setText(_translate("Form", "Size in mm from"))
        self.label_24.setText(_translate("Form", "or more then "))
        self.lineEdit_19.setText(_translate("Form", "6"))
        self.checkBox_8.setText(_translate("Form", "Use warning when pads less then"))
        self.checkBox_9.setText(_translate("Form", "Use warning when size in mm less then "))
        self.groupBox_9.setTitle(_translate("Form", "Group C"))
        self.lineEdit_20.setText(_translate("Form", "160"))
        self.lineEdit_21.setText(_translate("Form", "50"))
        self.lineEdit_22.setText(_translate("Form", "44"))
        self.label_25.setText(_translate("Form", "to"))
        self.lineEdit_23.setText(_translate("Form", "40"))
        self.lineEdit_24.setText(_translate("Form", "22"))
        self.label_26.setText(_translate("Form", "Pad count from "))
        self.label_27.setText(_translate("Form", "or more then "))
        self.label_28.setText(_translate("Form", "to"))
        self.lineEdit_25.setText(_translate("Form", "150"))
        self.lineEdit_26.setText(_translate("Form", "45"))
        self.label_29.setText(_translate("Form", "Size in mm from"))
        self.label_30.setText(_translate("Form", "or more then "))
        self.lineEdit_27.setText(_translate("Form", "20"))
        self.checkBox_10.setText(_translate("Form", "Use warning when pads less then"))
        self.checkBox_11.setText(_translate("Form", "Use warning when size in mm less then "))
        self.groupBox_10.setTitle(_translate("Form", "Group D"))
        self.checkBox_13.setText(_translate("Form", "Use warning when this group used"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_4), _translate("Form", "Groups"))
        self.lineEdit_37.setText(_translate("Form", "2"))
        self.lineEdit_38.setText(_translate("Form", "1"))
        self.label_46.setText(_translate("Form", "Max DIP pads for SMD component"))
        self.checkBox_5.setText(_translate("Form", "Use warning DIP pad count more then"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_5), _translate("Form", "DIP/SMD"))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("Form", "Layer 1"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("Form", "Layer 2"))
        item = self.tableWidget_6.verticalHeaderItem(2)
        item.setText(_translate("Form", "Layer 3"))
        item = self.tableWidget_6.verticalHeaderItem(3)
        item.setText(_translate("Form", "Layer 4"))
        item = self.tableWidget_6.verticalHeaderItem(4)
        item.setText(_translate("Form", "Layer 5"))
        item = self.tableWidget_6.verticalHeaderItem(5)
        item.setText(_translate("Form", "Layer 6"))
        item = self.tableWidget_6.verticalHeaderItem(6)
        item.setText(_translate("Form", "Layer 7"))
        item = self.tableWidget_6.verticalHeaderItem(7)
        item.setText(_translate("Form", "Layer 8"))
        item = self.tableWidget_6.verticalHeaderItem(8)
        item.setText(_translate("Form", "Layer 9"))
        item = self.tableWidget_6.verticalHeaderItem(9)
        item.setText(_translate("Form", "Layer 10"))
        item = self.tableWidget_6.verticalHeaderItem(10)
        item.setText(_translate("Form", "Layer 11"))
        item = self.tableWidget_6.verticalHeaderItem(11)
        item.setText(_translate("Form", "Layer 12"))
        item = self.tableWidget_6.verticalHeaderItem(12)
        item.setText(_translate("Form", "Layer 13"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Color"))
        self.tab_widget3.setTabText(self.tab_widget3.indexOf(self.tab_14), _translate("Form", "Colors"))
        self.pushButton_16.setText(_translate("Form", "Add"))
        self.pushButton_17.setText(_translate("Form", "Copy"))
        self.pushButton_18.setText(_translate("Form", "Delete"))
        self.groupBox_5.setTitle(_translate("Form", "Component tape"))
        self.label_42.setText(_translate("Form", "Image path"))
        self.label_39.setText(_translate("Form", "Name"))
        self.label_40.setText(_translate("Form", "Type"))
        self.label_41.setText(_translate("Form", "Pads"))
        self.pushButton_19.setText(_translate("Form", "..."))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Type"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Pads"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Image path"))
        self.tab_widget3.setTabText(self.tab_widget3.indexOf(self.tab_15), _translate("Form", "Component tapes"))
        self.labelCurrentSetting.setText(_translate("Form", "TextLabel"))
        self.settings_tree.headerItem().setText(0, _translate("Form", "1"))
        __sortingEnabled = self.settings_tree.isSortingEnabled()
        self.settings_tree.setSortingEnabled(False)
        self.settings_tree.topLevelItem(0).setText(0, _translate("Form", "General settings"))
        self.settings_tree.topLevelItem(0).child(0).setText(0, _translate("Form", "Settings import/export"))
        self.settings_tree.topLevelItem(0).child(1).setText(0, _translate("Form", "Hotkeys"))
        self.settings_tree.topLevelItem(0).child(2).setText(0, _translate("Form", "Toolbar"))
        self.settings_tree.topLevelItem(0).child(3).setText(0, _translate("Form", "View"))
        self.settings_tree.topLevelItem(0).child(4).setText(0, _translate("Form", "Logging"))
        self.settings_tree.topLevelItem(1).setText(0, _translate("Form", "Preprocessing"))
        self.settings_tree.topLevelItem(1).child(0).setText(0, _translate("Form", "Symbols replacement"))
        self.settings_tree.topLevelItem(1).child(1).setText(0, _translate("Form", "Font adding"))
        self.settings_tree.topLevelItem(1).child(2).setText(0, _translate("Form", "RefPointSize"))
        self.settings_tree.topLevelItem(1).child(3).setText(0, _translate("Form", "Solder swell"))
        self.settings_tree.topLevelItem(2).setText(0, _translate("Form", "Processing"))
        self.settings_tree.topLevelItem(2).child(0).setText(0, _translate("Form", "Attribute assigment"))
        self.settings_tree.topLevelItem(2).child(1).setText(0, _translate("Form", "Attribute types"))
        self.settings_tree.topLevelItem(2).child(2).setText(0, _translate("Form", "PnP"))
        self.settings_tree.topLevelItem(2).child(3).setText(0, _translate("Form", "Groups"))
        self.settings_tree.topLevelItem(2).child(4).setText(0, _translate("Form", "DIP/SMD"))
        self.settings_tree.topLevelItem(3).setText(0, _translate("Form", "Drawing"))
        self.settings_tree.topLevelItem(3).child(0).setText(0, _translate("Form", "Colors"))
        self.settings_tree.topLevelItem(3).child(1).setText(0, _translate("Form", "Component tapes"))
        self.settings_tree.setSortingEnabled(__sortingEnabled)
