# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1163, 694)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page0)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tab_widget0 = QtWidgets.QTabWidget(self.page0)
        self.tab_widget0.setObjectName("tab_widget0")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tab_widget0.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tab_widget0.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tab_widget0.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tab_widget0.addTab(self.tab_9, "")
        self.gridLayout_7.addWidget(self.tab_widget0, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tab_widget1 = QtWidgets.QTabWidget(self.page1)
        self.tab_widget1.setObjectName("tab_widget1")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tab_widget1.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tab_widget1.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tab_widget1.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tab_widget1.addTab(self.tab_13, "")
        self.gridLayout_8.addWidget(self.tab_widget1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab_widget2 = QtWidgets.QTabWidget(self.page2)
        self.tab_widget2.setObjectName("tab_widget2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout_6.addWidget(self.tableWidget, 0, 0, 4, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 280, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 4, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 2, 6, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 3, 1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_6.addWidget(self.groupBox, 4, 0, 1, 2)
        self.tab_widget2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 1, 2, 3, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_5.addWidget(self.checkBox_3, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_5.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 3, 1, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.gridLayout_4.addWidget(self.tableWidget_4, 0, 0, 4, 1)
        self.tab_widget2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_36.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_15.addWidget(self.lineEdit_36, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 564, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem3, 1, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_15.addWidget(self.checkBox_4, 1, 0, 1, 1)
        self.tab_widget2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_11.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_11.addWidget(self.lineEdit_11, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_11.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_11.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_11.addWidget(self.lineEdit_9, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 1, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_11.addWidget(self.lineEdit_10, 2, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_11.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 2, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_11.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_11.addWidget(self.checkBox_6, 2, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_11.addWidget(self.checkBox_7, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_12.addWidget(self.lineEdit_12, 0, 3, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_12.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_12.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 0, 2, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_12.addWidget(self.lineEdit_15, 3, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_12.addWidget(self.lineEdit_16, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 1, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_12.addWidget(self.lineEdit_17, 2, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_12.addWidget(self.lineEdit_18, 1, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        self.label_24.setObjectName("label_24")
        self.gridLayout_12.addWidget(self.label_24, 2, 2, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_12.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_12.addWidget(self.checkBox_8, 2, 0, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_12.addWidget(self.checkBox_9, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_13.addWidget(self.lineEdit_20, 0, 3, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_13.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_13.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 0, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_13.addWidget(self.lineEdit_23, 3, 3, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_13.addWidget(self.lineEdit_24, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setObjectName("label_26")
        self.gridLayout_13.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 3, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 1, 2, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_13.addWidget(self.lineEdit_25, 2, 3, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_13.addWidget(self.lineEdit_26, 1, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_9)
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_9)
        self.label_30.setObjectName("label_30")
        self.gridLayout_13.addWidget(self.label_30, 2, 2, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_13.addWidget(self.lineEdit_27, 1, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_13.addWidget(self.checkBox_10, 2, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_13.addWidget(self.checkBox_11, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_14.addWidget(self.checkBox_13, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_10, 3, 0, 1, 1)
        self.tab_widget2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_37.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_16.addWidget(self.lineEdit_37, 0, 2, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_38.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_16.addWidget(self.lineEdit_38, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(539, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem4, 2, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_16.addWidget(self.label_46, 0, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_16.addWidget(self.checkBox_5, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 533, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem5, 3, 0, 1, 1)
        self.tab_widget2.addTab(self.tab_5, "")
        self.gridLayout_2.addWidget(self.tab_widget2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tab_widget3 = QtWidgets.QTabWidget(self.page3)
        self.tab_widget3.setObjectName("tab_widget3")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tab_widget3.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tab_widget3.addTab(self.tab_15, "")
        self.gridLayout_9.addWidget(self.tab_widget3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page3)
        self.gridLayout.addWidget(self.stackedWidget, 1, 1, 1, 1)
        self.labelCurrentSetting = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelCurrentSetting.setFont(font)
        self.labelCurrentSetting.setObjectName("labelCurrentSetting")
        self.gridLayout.addWidget(self.labelCurrentSetting, 0, 1, 1, 1)
        self.settings_tree = QtWidgets.QTreeWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.settings_tree.setFont(font)
        self.settings_tree.setObjectName("settings_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.settings_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.settings_tree.header().setVisible(False)
        self.gridLayout.addWidget(self.settings_tree, 0, 0, 2, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.tab_widget0.setCurrentIndex(0)
        self.tab_widget1.setCurrentIndex(0)
        self.tab_widget2.setCurrentIndex(0)
        self.tab_widget3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_6), _translate("Form", "Settings import/export"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_7), _translate("Form", "Hotkeys"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_8), _translate("Form", "Toolbar"))
        self.tab_widget0.setTabText(self.tab_widget0.indexOf(self.tab_9), _translate("Form", "View"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_10), _translate("Form", "Symbols replacement"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_11), _translate("Form", "Font adding"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_12), _translate("Form", "RefPointSize"))
        self.tab_widget1.setTabText(self.tab_widget1.indexOf(self.tab_13), _translate("Form", "Solder swell"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Use"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Text"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Ignore"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "DIP/SMD"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "CompType"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Attribute List"))
        self.pushButton_4.setText(_translate("Form", "Add"))
        self.pushButton_5.setText(_translate("Form", "Copy"))
        self.pushButton_6.setText(_translate("Form", "Delete"))
        self.groupBox.setTitle(_translate("Form", "Component"))
        self.label_4.setText(_translate("Form", "Type"))
        self.label_3.setText(_translate("Form", "CompType"))
        self.label_2.setText(_translate("Form", "DIP/SMD"))
        self.label_6.setText(_translate("Form", "Use"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Attribute"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Default Value"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Visible"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Side"))
        self.label_7.setText(_translate("Form", "Ignore"))
        self.label_5.setText(_translate("Form", "Text"))
        self.pushButton_7.setText(_translate("Form", "Add"))
        self.pushButton_8.setText(_translate("Form", "Copy"))
        self.pushButton_9.setText(_translate("Form", "Delete"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab), _translate("Form", "Attribute assigment"))
        self.pushButton_2.setText(_translate("Form", "Copy"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.groupBox_2.setTitle(_translate("Form", "Attribute"))
        self.label_8.setText(_translate("Form", "Attribute"))
        self.label_12.setText(_translate("Form", "Description"))
        self.label_9.setText(_translate("Form", "Default Value"))
        self.label_10.setText(_translate("Form", "Visible"))
        self.label_11.setText(_translate("Form", "Side"))
        self.pushButton_3.setText(_translate("Form", "Delete"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Attribute"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Default Value"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Visible"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Side"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Description"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_2), _translate("Form", "Attribute types"))
        self.lineEdit_36.setText(_translate("Form", "2"))
        self.checkBox_4.setText(_translate("Form", "Use warning  distance between arithmetic and geometric centers in mm"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_3), _translate("Form", "PnP"))
        self.groupBox_7.setTitle(_translate("Form", "Group A"))
        self.lineEdit_5.setText(_translate("Form", "8"))
        self.lineEdit_11.setText(_translate("Form", "2"))
        self.lineEdit_4.setText(_translate("Form", "0"))
        self.label_14.setText(_translate("Form", "to"))
        self.lineEdit_8.setText(_translate("Form", "5"))
        self.lineEdit_9.setText(_translate("Form", "1"))
        self.label_13.setText(_translate("Form", "Pad count from "))
        self.label_19.setText(_translate("Form", "or more then "))
        self.label_16.setText(_translate("Form", "to"))
        self.lineEdit_10.setText(_translate("Form", "6"))
        self.lineEdit_6.setText(_translate("Form", "6"))
        self.label_15.setText(_translate("Form", "Size in mm from"))
        self.label_20.setText(_translate("Form", "or more then "))
        self.lineEdit_7.setText(_translate("Form", "0"))
        self.checkBox_6.setText(_translate("Form", "Use warning when pads less then"))
        self.checkBox_7.setText(_translate("Form", "Use warning when size in mm less then "))
        self.groupBox_8.setTitle(_translate("Form", "Group B"))
        self.lineEdit_12.setText(_translate("Form", "44"))
        self.lineEdit_13.setText(_translate("Form", "10"))
        self.lineEdit_14.setText(_translate("Form", "8"))
        self.label_17.setText(_translate("Form", "to"))
        self.lineEdit_15.setText(_translate("Form", "18"))
        self.lineEdit_16.setText(_translate("Form", "8"))
        self.label_18.setText(_translate("Form", "Pad count from "))
        self.label_21.setText(_translate("Form", "or more then "))
        self.label_22.setText(_translate("Form", "to"))
        self.lineEdit_17.setText(_translate("Form", "40"))
        self.lineEdit_18.setText(_translate("Form", "20"))
        self.label_23.setText(_translate("Form", "Size in mm from"))
        self.label_24.setText(_translate("Form", "or more then "))
        self.lineEdit_19.setText(_translate("Form", "6"))
        self.checkBox_8.setText(_translate("Form", "Use warning when pads less then"))
        self.checkBox_9.setText(_translate("Form", "Use warning when size in mm less then "))
        self.groupBox_9.setTitle(_translate("Form", "Group C"))
        self.lineEdit_20.setText(_translate("Form", "160"))
        self.lineEdit_21.setText(_translate("Form", "50"))
        self.lineEdit_22.setText(_translate("Form", "44"))
        self.label_25.setText(_translate("Form", "to"))
        self.lineEdit_23.setText(_translate("Form", "40"))
        self.lineEdit_24.setText(_translate("Form", "22"))
        self.label_26.setText(_translate("Form", "Pad count from "))
        self.label_27.setText(_translate("Form", "or more then "))
        self.label_28.setText(_translate("Form", "to"))
        self.lineEdit_25.setText(_translate("Form", "150"))
        self.lineEdit_26.setText(_translate("Form", "45"))
        self.label_29.setText(_translate("Form", "Size in mm from"))
        self.label_30.setText(_translate("Form", "or more then "))
        self.lineEdit_27.setText(_translate("Form", "20"))
        self.checkBox_10.setText(_translate("Form", "Use warning when pads less then"))
        self.checkBox_11.setText(_translate("Form", "Use warning when size in mm less then "))
        self.groupBox_10.setTitle(_translate("Form", "Group D"))
        self.checkBox_13.setText(_translate("Form", "Use warning when this group used"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_4), _translate("Form", "Groups"))
        self.lineEdit_37.setText(_translate("Form", "2"))
        self.lineEdit_38.setText(_translate("Form", "1"))
        self.label_46.setText(_translate("Form", "Max DIP pads for SMD component"))
        self.checkBox_5.setText(_translate("Form", "Use warning DIP pad count more then"))
        self.tab_widget2.setTabText(self.tab_widget2.indexOf(self.tab_5), _translate("Form", "DIP/SMD"))
        self.tab_widget3.setTabText(self.tab_widget3.indexOf(self.tab_14), _translate("Form", "Colors"))
        self.tab_widget3.setTabText(self.tab_widget3.indexOf(self.tab_15), _translate("Form", "Component tapes"))
        self.labelCurrentSetting.setText(_translate("Form", "TextLabel"))
        self.settings_tree.headerItem().setText(0, _translate("Form", "1"))
        __sortingEnabled = self.settings_tree.isSortingEnabled()
        self.settings_tree.setSortingEnabled(False)
        self.settings_tree.topLevelItem(0).setText(0, _translate("Form", "General settings"))
        self.settings_tree.topLevelItem(0).child(0).setText(0, _translate("Form", "Settings import/export"))
        self.settings_tree.topLevelItem(0).child(1).setText(0, _translate("Form", "Hotkeys"))
        self.settings_tree.topLevelItem(0).child(2).setText(0, _translate("Form", "Toolbar"))
        self.settings_tree.topLevelItem(0).child(3).setText(0, _translate("Form", "View"))
        self.settings_tree.topLevelItem(1).setText(0, _translate("Form", "Preprocessing"))
        self.settings_tree.topLevelItem(1).child(0).setText(0, _translate("Form", "Symbols replacement"))
        self.settings_tree.topLevelItem(1).child(1).setText(0, _translate("Form", "Font adding"))
        self.settings_tree.topLevelItem(1).child(2).setText(0, _translate("Form", "RefPointSize"))
        self.settings_tree.topLevelItem(1).child(3).setText(0, _translate("Form", "Solder swell"))
        self.settings_tree.topLevelItem(2).setText(0, _translate("Form", "Processing"))
        self.settings_tree.topLevelItem(2).child(0).setText(0, _translate("Form", "Attribute assigment"))
        self.settings_tree.topLevelItem(2).child(1).setText(0, _translate("Form", "Attribute types"))
        self.settings_tree.topLevelItem(2).child(2).setText(0, _translate("Form", "PnP"))
        self.settings_tree.topLevelItem(2).child(3).setText(0, _translate("Form", "Groups"))
        self.settings_tree.topLevelItem(2).child(4).setText(0, _translate("Form", "DIP/SMD"))
        self.settings_tree.topLevelItem(3).setText(0, _translate("Form", "Drawing"))
        self.settings_tree.topLevelItem(3).child(0).setText(0, _translate("Form", "Colors"))
        self.settings_tree.topLevelItem(3).child(1).setText(0, _translate("Form", "Component tapes"))
        self.settings_tree.setSortingEnabled(__sortingEnabled)
